name: Build with GraalVM Native Image
on: [push]
env:
  MX_PYTHON: python3.8
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native Game of Life
        run: |
          mvn --no-transfer-progress -Pnative package
          cp ./target/game-of-life ./

      - name: Run Game of Life demo in JIT vs. AOT modes
        run: |
          $GRAALVM_HOME/bin/java --enable-preview -cp target/classes/ gameoflife.Main patterns/puffer_train.txt 0 -1 10 91 10 91 true true
          ./game-of-life patterns/puffer_train.txt 0 -1 10 91 10 91 true true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: game-of-life-${{ matrix.os }}
          path: |
            game-of-life
            patterns/*
